apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: openlap-analyticsframework-
labels:
- pairs:
    app.kubernetes.io/component: openlap-analyticsframework
  includeSelectors: true
  includeTemplates: true

resources:
- mongo
- web
