apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- pairs:
    service: web
  includeSelectors: true
  includeTemplates: true

resources:
- deployment.yaml
- service.yaml

secretGenerator:
- name: web
  literals:
  - ADMIN_EMAIL=admin@mail.com
  - ADMIN_NAME=admin
  # - ADMIN_PASSWORD=1234qweR
  # - JWT_SECRET_KEY=secret
