apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- pairs:
    app.kubernetes.io/component: openlap-indicatoreditor
  includeSelectors: true
  includeTemplates: true

namePrefix: openlap-indicatoreditor-

resources:
- deployment.yaml
- service.yaml
