apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- pairs:
    service: mongo
  includeSelectors: true
  includeTemplates: true

resources:
- deployment.yaml
- pvc.yaml
- service.yaml

vars:
- name: OPENLAP_OFFICIAL_OPENLAP_ANALYTICSFRAMEWORK_MONGO_SERVICE
  objref:
    apiVersion: v1
    kind: Service
    name: mongo
