name: Continuous Integration

on:
  push:
    branches:   [ main ]
  pull_request:
    branches:   [ main ]

jobs:
  images:
    name: Build container images
    uses: ./.github/workflows/build.yml
    with:
      project_desc:    ${{ github.event.repository.name }}
      base_image_name: ghcr.io/${{ github.repository }}-
      services:        '[ "openlap-analyticsframework", "openlap-indicatoreditor" ]'
      push:            ${{ github.event_name != 'pull_request' }}
      registry_host:   ghcr.io
      registry_user:   ${{ github.actor }}
    secrets:
      registry_token:  ${{ secrets.GITHUB_TOKEN }}
